### ISSUE TITLE
How to use the generated refs?

### ISSUE THREAD

**Issue by alexej-d** [sandiiarov/use-popper#21]
What if one needs to reuse the generated refference's ref for another effect like this https://streamich.github.io/react-use/?path=/story/ui-useclickaway--docs?

As I see, refference.ref and popper.ref are just functions so it is not possible to access their current prop from outside to target the DOM element.

**Comment by sandiiarov** [comment]
I am using mergeRefs helper
```js
function mergeRefs(...refs) {
  return ref => {
    refs.forEach(resolvableRef => {
      if (typeof resolvableRef === 'function') {
        resolvableRef(ref);
      }

      if (resolvableRef) {
        resolvableRef.current = ref;
      }
    });
  };
}
```
https://codesandbox.io/s/0qjk4w5v0l

**Comment by alexej-d** [comment]
Great, didn't know this was possible, thanks!
