### ISSUE TITLE
Current npm package has no dist files

### ISSUE THREAD

**Issue by alexej-d** [sandiiarov/use-popper#24]
Version 1.1.4 only downloads the .ts files

**Comment by hellosmithy** [comment]
Are there any plans to resolve this? The package is pretty much unusable in standard build workflows that usually ignore node_modules when transpiling TS

**Comment by hellosmithy** [comment]
Created a PR at https://github.com/sandiiarov/use-popper/pull/27

**Comment by sandiiarov** [comment]
It was my fault. I have published the wrong src files. Let me fix it.

**Comment by sandiiarov** [comment]
I've published a new version [1.1.5](https://runpkg.com/?use-popper) with dist files
